spring.application.name=TestingApplication

#DB Confgiuration
spring.datasource.url=jdbc:postgresql://postgres-spring-1.cvmgwokw6ub4.eu-north-1.rds.amazonaws.com/postgres
spring.datasource.username=root
spring.datasource.password=postgres-1
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true


my.variable=prod